import type { Recipe } from "./types";

export const CATALOG_RECIPES: Record<string, Recipe> = {
  "wraps-poulet": {
    servings: 4,
    ingredients: [
      { name: "blancs de poulet", quantity: 500, unit: "g" },
      { name: "tortillas", quantity: 8, unit: "" },
      { name: "laitue", quantity: 1, unit: "" },
      { name: "tomates", quantity: 2, unit: "" },
      { name: "concombre", quantity: 1, unit: "" },
      { name: "yaourt grec", quantity: 150, unit: "g" },
      { name: "citron", quantity: 0.5, unit: "" },
      { name: "paprika", quantity: 1, unit: "c. à café" },
      { name: "huile d'olive", quantity: 1, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Couper le poulet en lanières et le mélanger avec l'huile, le paprika, le sel et le poivre.",
      "Faire dorer le poulet à la poêle 8 à 10 minutes.",
      "Mélanger le yaourt avec le jus de citron, un peu de sel et de poivre.",
      "Garnir les tortillas de salade, tomate, concombre et poulet. Ajouter la sauce, rouler et servir.",
    ],
  },
  "bowl-poulet-riz": {
    servings: 4,
    ingredients: [
      { name: "blancs de poulet", quantity: 500, unit: "g" },
      { name: "riz", quantity: 250, unit: "g" },
      { name: "concombre", quantity: 1, unit: "" },
      { name: "carottes", quantity: 2, unit: "" },
      { name: "maïs", quantity: 150, unit: "g" },
      { name: "sauce soja", quantity: 2, unit: "c. à soupe" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "citron vert", quantity: 1, unit: "" },
    ],
    steps: [
      "Cuire le riz selon les indications du paquet.",
      "Couper le poulet en dés et le faire dorer dans l'huile. Ajouter la sauce soja et cuire encore 2 minutes.",
      "Râper les carottes et couper le concombre.",
      "Répartir le riz dans les bols, puis ajouter poulet, crudités et maïs. Arroser d'un peu de citron vert.",
    ],
  },
  "poulet-airfryer": {
    servings: 4,
    ingredients: [
      { name: "blancs de poulet", quantity: 600, unit: "g" },
      { name: "chapelure", quantity: 80, unit: "g" },
      { name: "farine", quantity: 40, unit: "g" },
      { name: "œuf", quantity: 1, unit: "" },
      { name: "paprika", quantity: 1, unit: "c. à café" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Couper le poulet en morceaux.",
      "Préparer trois assiettes : farine assaisonnée, œuf battu, chapelure mélangée au paprika.",
      "Passer chaque morceau dans la farine, l'œuf puis la chapelure.",
      "Déposer dans l'Airfryer, arroser légèrement d'huile et cuire à 190 °C environ 12 à 15 minutes, en retournant à mi-cuisson.",
    ],
  },
  "poulet-curry": {
    servings: 4,
    ingredients: [
      { name: "blancs de poulet", quantity: 600, unit: "g" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "gousses d'ail", quantity: 2, unit: "" },
      { name: "lait de coco", quantity: 400, unit: "ml" },
      { name: "pâte de curry doux", quantity: 2, unit: "c. à soupe" },
      { name: "courgette", quantity: 1, unit: "" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "riz", quantity: 250, unit: "g" },
      { name: "sel", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Cuire le riz.",
      "Faire revenir l'oignon émincé dans l'huile 3 minutes. Ajouter l'ail et la pâte de curry.",
      "Ajouter le poulet en morceaux et faire dorer quelques minutes.",
      "Ajouter la courgette puis le lait de coco. Laisser mijoter 12 à 15 minutes. Servir avec le riz.",
    ],
  },
  "bowl-poulet-medit": {
    servings: 4,
    ingredients: [
      { name: "poulet", quantity: 500, unit: "g" },
      { name: "semoule", quantity: 250, unit: "g" },
      { name: "concombre", quantity: 1, unit: "" },
      { name: "tomates cerises", quantity: 250, unit: "g" },
      { name: "feta", quantity: 100, unit: "g" },
      { name: "olives", quantity: 100, unit: "g" },
      { name: "citron", quantity: 1, unit: "" },
      { name: "huile d'olive", quantity: 2, unit: "c. à soupe" },
      { name: "origan", quantity: 1, unit: "c. à café" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Cuire la semoule et l'égrener.",
      "Faire dorer le poulet en dés avec l'huile, l'origan, le sel et le poivre.",
      "Couper concombre et tomates.",
      "Répartir la semoule dans les bols. Ajouter poulet, légumes, feta et olives. Arroser de citron et d'huile d'olive.",
    ],
  },
  "poulet-basquaise": {
    servings: 4,
    ingredients: [
      { name: "poulet", quantity: 600, unit: "g" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "poivron rouge", quantity: 1, unit: "" },
      { name: "poivron vert", quantity: 1, unit: "" },
      { name: "tomates concassées", quantity: 400, unit: "g" },
      { name: "gousses d'ail", quantity: 2, unit: "" },
      { name: "paprika", quantity: 1, unit: "c. à café" },
      { name: "huile d'olive", quantity: 2, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Faire dorer le poulet dans l'huile puis le réserver.",
      "Faire revenir l'oignon et les poivrons émincés 5 minutes.",
      "Ajouter l'ail, le paprika et les tomates.",
      "Remettre le poulet, couvrir et laisser mijoter 25 minutes. Servir avec du riz ou du pain.",
    ],
  },
  "poulet-citron-cocotte": {
    servings: 4,
    ingredients: [
      { name: "blancs ou hauts de cuisses de poulet", quantity: 600, unit: "g" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "citrons", quantity: 2, unit: "" },
      { name: "gousses d'ail", quantity: 2, unit: "" },
      { name: "bouillon", quantity: 150, unit: "ml" },
      { name: "huile d'olive", quantity: 1, unit: "c. à soupe" },
      { name: "thym", quantity: 1, unit: "c. à café" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Faire chauffer l'huile dans la cocotte et dorer le poulet.",
      "Ajouter l'oignon émincé et l'ail, puis cuire 3 minutes.",
      "Verser le bouillon et ajouter le jus d'un citron, le thym, le sel et le poivre.",
      "Couvrir et laisser mijoter 20 minutes. Ajouter quelques rondelles du second citron en fin de cuisson.",
    ],
  },
  "brochettes-poulet-plancha": {
    servings: 4,
    ingredients: [
      { name: "poulet", quantity: 600, unit: "g" },
      { name: "poivron rouge", quantity: 1, unit: "" },
      { name: "courgette", quantity: 1, unit: "" },
      { name: "oignon rouge", quantity: 1, unit: "" },
      { name: "huile d'olive", quantity: 2, unit: "c. à soupe" },
      { name: "citron", quantity: 1, unit: "" },
      { name: "paprika", quantity: 1, unit: "c. à café" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Couper le poulet et les légumes en morceaux.",
      "Mélanger l'huile, le jus de citron, le paprika, le sel et le poivre. Ajouter le poulet et laisser mariner 15 minutes.",
      "Monter les brochettes en alternant poulet et légumes.",
      "Cuire à la plancha bien chaude 10 à 12 minutes en retournant régulièrement.",
    ],
  },
  "steak-hache-puree": {
    servings: 4,
    ingredients: [
      { name: "steaks hachés", quantity: 4, unit: "" },
      { name: "pommes de terre", quantity: 1, unit: "kg" },
      { name: "lait", quantity: 15, unit: "cl" },
      { name: "beurre", quantity: 40, unit: "g" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Éplucher les pommes de terre, les couper et les cuire 20 minutes dans l'eau salée.",
      "Les écraser avec le beurre et le lait chaud. Saler et poivrer.",
      "Cuire les steaks dans l'huile selon la cuisson souhaitée.",
      "Servir avec la purée.",
    ],
  },
  "boeuf-bourguignon": {
    servings: 4,
    ingredients: [
      { name: "bœuf à mijoter", quantity: 800, unit: "g" },
      { name: "lardons", quantity: 150, unit: "g" },
      { name: "carottes", quantity: 2, unit: "" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "vin rouge", quantity: 500, unit: "ml" },
      { name: "bouillon", quantity: 250, unit: "ml" },
      { name: "champignons", quantity: 200, unit: "g" },
      { name: "farine", quantity: 1, unit: "c. à soupe" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Faire dorer le bœuf dans l'huile puis réserver.",
      "Faire revenir lardons, oignon et carottes. Ajouter la farine.",
      "Remettre le bœuf, verser le vin et le bouillon.",
      "Couvrir et mijoter environ 2 heures. Ajouter les champignons sur les 20 dernières minutes.",
    ],
  },
  "tacos-boeuf": {
    servings: 4,
    ingredients: [
      { name: "bœuf haché", quantity: 400, unit: "g" },
      { name: "tortillas", quantity: 8, unit: "" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "tomate", quantity: 1, unit: "" },
      { name: "laitue", quantity: 0.5, unit: "" },
      { name: "cheddar râpé", quantity: 100, unit: "g" },
      { name: "paprika", quantity: 1, unit: "c. à café" },
      { name: "cumin", quantity: 0.5, unit: "c. à café" },
      { name: "huile", quantity: 2, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Faire revenir l'oignon dans l'huile puis ajouter le bœuf.",
      "Ajouter paprika, cumin, sel et poivre et cuire 6 à 8 minutes.",
      "Réchauffer les tortillas.",
      "Garnir de viande, laitue, tomate et cheddar.",
    ],
  },
  "hachis-parmentier": {
    servings: 4,
    ingredients: [
      { name: "bœuf haché", quantity: 600, unit: "g" },
      { name: "pommes de terre", quantity: 1, unit: "kg" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "carottes", quantity: 2, unit: "" },
      { name: "lait", quantity: 15, unit: "cl" },
      { name: "beurre", quantity: 40, unit: "g" },
      { name: "fromage râpé", quantity: 50, unit: "g" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Préparer une purée avec les pommes de terre, le lait et le beurre.",
      "Faire revenir oignon et carottes. Ajouter le bœuf et cuire 8 minutes.",
      "Répartir la viande dans un plat puis couvrir de purée.",
      "Parsemer de fromage et gratiner à 200 °C pendant 20 minutes.",
    ],
  },
  "brochettes-boeuf-bbq": {
    servings: 4,
    ingredients: [
      { name: "bœuf à griller", quantity: 600, unit: "g" },
      { name: "poivron", quantity: 1, unit: "" },
      { name: "courgette", quantity: 1, unit: "" },
      { name: "oignon rouge", quantity: 1, unit: "" },
      { name: "huile d'olive", quantity: 2, unit: "c. à soupe" },
      { name: "sauce soja", quantity: 1, unit: "c. à soupe" },
      { name: "paprika", quantity: 1, unit: "c. à café" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Couper viande et légumes en morceaux.",
      "Mélanger huile, sauce soja et paprika avec la viande.",
      "Monter les brochettes.",
      "Cuire au barbecue ou à la plancha 8 à 10 minutes selon la cuisson souhaitée.",
    ],
  },
  "keftas-agneau": {
    servings: 4,
    ingredients: [
      { name: "agneau haché", quantity: 500, unit: "g" },
      { name: "petit oignon", quantity: 1, unit: "" },
      { name: "gousses d'ail", quantity: 2, unit: "" },
      { name: "cumin", quantity: 1, unit: "c. à café" },
      { name: "paprika", quantity: 1, unit: "c. à café" },
      { name: "persil", quantity: 0.5, unit: "bouquet" },
      { name: "semoule", quantity: 250, unit: "g" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Mélanger l'agneau avec oignon finement haché, ail, persil et épices.",
      "Former des boulettes allongées.",
      "Cuire à la poêle ou à la plancha avec l'huile 8 à 10 minutes.",
      "Préparer la semoule et servir avec les keftas.",
    ],
  },
  "boeuf-saute-asiat": {
    servings: 4,
    ingredients: [
      { name: "bœuf émincé", quantity: 500, unit: "g" },
      { name: "poivron", quantity: 1, unit: "" },
      { name: "carottes", quantity: 2, unit: "" },
      { name: "brocoli", quantity: 1, unit: "" },
      { name: "gousses d'ail", quantity: 2, unit: "" },
      { name: "sauce soja", quantity: 3, unit: "c. à soupe" },
      { name: "huile de sésame", quantity: 1, unit: "c. à soupe" },
      { name: "huile neutre", quantity: 1, unit: "c. à soupe" },
      { name: "riz", quantity: 250, unit: "g" },
    ],
    steps: [
      "Cuire le riz.",
      "Saisir le bœuf très rapidement dans l'huile chaude puis réserver.",
      "Faire sauter les légumes avec l'ail 5 à 6 minutes.",
      "Remettre le bœuf, ajouter sauce soja et huile de sésame. Mélanger 2 minutes et servir avec le riz.",
    ],
  },
  "croque-monsieur": {
    servings: 4,
    ingredients: [
      { name: "pain de mie", quantity: 8, unit: "tranches" },
      { name: "jambon", quantity: 4, unit: "tranches" },
      { name: "fromage râpé", quantity: 120, unit: "g" },
      { name: "beurre", quantity: 20, unit: "g" },
      { name: "moutarde", quantity: 1, unit: "c. à café" },
      { name: "salade verte", quantity: 1, unit: "", scalable: false },
      { name: "vinaigre", quantity: 1, unit: "c. à soupe" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
    ],
    steps: [
      "Tartiner légèrement le pain de moutarde, ajouter jambon et fromage puis refermer.",
      "Beurrer légèrement l'extérieur des croques.",
      "Cuire au four à 200 °C 10 à 12 minutes ou dans une poêle couverte jusqu'à ce que le fromage fonde.",
      "Préparer la salade et servir avec les croques.",
    ],
  },
  "pates-carbonara": {
    servings: 4,
    ingredients: [
      { name: "spaghetti", quantity: 400, unit: "g" },
      { name: "lardons", quantity: 150, unit: "g" },
      { name: "jaunes d'œufs", quantity: 3, unit: "" },
      { name: "parmesan râpé", quantity: 80, unit: "g" },
      { name: "poivre noir", quantity: 0, unit: "", scalable: false },
      { name: "sel", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Cuire les pâtes dans une grande casserole d'eau salée.",
      "Faire dorer les lardons à la poêle.",
      "Mélanger jaunes d'œufs, parmesan et beaucoup de poivre.",
      "Égoutter les pâtes en gardant une louche d'eau de cuisson. Hors du feu, mélanger avec les lardons et la sauce aux œufs en ajoutant un peu d'eau pour obtenir une sauce crémeuse.",
    ],
  },
  "quiche-lorraine": {
    servings: 4,
    ingredients: [
      { name: "pâte brisée", quantity: 1, unit: "", scalable: false },
      { name: "lardons", quantity: 200, unit: "g" },
      { name: "œufs", quantity: 3, unit: "" },
      { name: "crème", quantity: 25, unit: "cl" },
      { name: "lait", quantity: 25, unit: "cl" },
      { name: "fromage râpé", quantity: 100, unit: "g" },
      { name: "muscade", quantity: 1, unit: "pincée" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Préchauffer le four à 180 °C et foncer le moule avec la pâte.",
      "Faire revenir les lardons puis les égoutter.",
      "Battre les œufs avec crème, lait, muscade, sel et poivre.",
      "Répartir lardons et fromage sur la pâte, verser l'appareil et cuire 35 à 40 minutes.",
    ],
  },
  "raclette": {
    servings: 4,
    ingredients: [
      { name: "pommes de terre", quantity: 800, unit: "g" },
      { name: "fromage à raclette", quantity: 600, unit: "g" },
      { name: "charcuterie", quantity: 200, unit: "g" },
      { name: "cornichons", quantity: 0, unit: "", scalable: false },
      { name: "petits oignons au vinaigre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Cuire les pommes de terre avec leur peau jusqu'à ce qu'elles soient tendres.",
      "Préparer charcuterie, cornichons et oignons sur la table.",
      "Faire fondre le fromage à raclette.",
      "Servir chacun avec pommes de terre, fromage et accompagnements.",
    ],
  },
  "saute-porc-caramel": {
    servings: 4,
    ingredients: [
      { name: "échine ou filet de porc", quantity: 600, unit: "g" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "gousses d'ail", quantity: 2, unit: "" },
      { name: "sauce soja", quantity: 3, unit: "c. à soupe" },
      { name: "miel", quantity: 2, unit: "c. à soupe" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "riz", quantity: 250, unit: "g" },
      { name: "vinaigre de riz", quantity: 1, unit: "c. à soupe" },
    ],
    steps: [
      "Cuire le riz.",
      "Couper le porc en petits morceaux et le faire dorer dans l'huile.",
      "Ajouter oignon et ail puis cuire 3 minutes.",
      "Ajouter soja, miel et vinaigre. Laisser caraméliser 5 minutes. Servir avec le riz.",
    ],
  },
  "cabillaud-airfryer": {
    servings: 4,
    ingredients: [
      { name: "filets de cabillaud", quantity: 600, unit: "g" },
      { name: "chapelure", quantity: 80, unit: "g" },
      { name: "farine", quantity: 40, unit: "g" },
      { name: "œuf", quantity: 1, unit: "" },
      { name: "citron", quantity: 1, unit: "" },
      { name: "paprika", quantity: 1, unit: "c. à café" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Saler et poivrer le cabillaud.",
      "Passer chaque filet dans la farine, puis l'œuf battu et la chapelure mélangée au paprika.",
      "Déposer dans l'Airfryer, arroser légèrement d'huile et cuire à 190 °C 10 à 12 minutes.",
      "Servir avec du citron.",
    ],
  },
  "pates-thon": {
    servings: 4,
    ingredients: [
      { name: "pâtes", quantity: 400, unit: "g" },
      { name: "thon au naturel", quantity: 2, unit: "boîte" },
      { name: "tomates concassées", quantity: 400, unit: "g" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "gousses d'ail", quantity: 2, unit: "" },
      { name: "huile d'olive", quantity: 1, unit: "c. à soupe" },
      { name: "origan", quantity: 1, unit: "c. à café" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Cuire les pâtes.",
      "Faire revenir l'oignon et l'ail dans l'huile.",
      "Ajouter tomates, origan, sel et poivre et mijoter 10 minutes.",
      "Ajouter le thon émietté puis les pâtes égouttées. Mélanger et servir.",
    ],
  },
  "papillote-poisson": {
    servings: 4,
    ingredients: [
      { name: "filets de poisson blanc", quantity: 600, unit: "g" },
      { name: "courgettes", quantity: 2, unit: "" },
      { name: "carottes", quantity: 2, unit: "" },
      { name: "citron", quantity: 1, unit: "" },
      { name: "huile d'olive", quantity: 2, unit: "c. à soupe" },
      { name: "herbes de Provence", quantity: 1, unit: "c. à café" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Préchauffer le four à 190 °C.",
      "Émincer les légumes finement.",
      "Répartir poisson et légumes sur quatre grandes feuilles de papier cuisson. Ajouter huile, citron, herbes, sel et poivre.",
      "Fermer les papillotes et cuire 18 à 20 minutes.",
    ],
  },
  "risotto-crevettes": {
    servings: 4,
    ingredients: [
      { name: "riz arborio", quantity: 300, unit: "g" },
      { name: "crevettes décortiquées", quantity: 400, unit: "g" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "courgette", quantity: 1, unit: "" },
      { name: "bouillon de légumes", quantity: 1, unit: "l" },
      { name: "vin blanc", quantity: 10, unit: "cl" },
      { name: "parmesan", quantity: 30, unit: "g" },
      { name: "huile d'olive", quantity: 2, unit: "c. à soupe" },
    ],
    steps: [
      "Faire chauffer le bouillon.",
      "Faire revenir l'oignon dans l'huile puis ajouter le riz. Nacrer 2 minutes.",
      "Verser le vin puis ajouter le bouillon louche par louche en remuant, environ 18 minutes.",
      "Ajouter courgette en petits dés puis les crevettes sur les 5 dernières minutes. Finir avec le parmesan.",
    ],
  },
  "gambas-plancha": {
    servings: 4,
    ingredients: [
      { name: "gambas", quantity: 600, unit: "g" },
      { name: "gousses d'ail", quantity: 2, unit: "" },
      { name: "citron", quantity: 1, unit: "" },
      { name: "huile d'olive", quantity: 2, unit: "c. à soupe" },
      { name: "persil", quantity: 0.5, unit: "bouquet" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Mélanger gambas, huile, ail, jus de citron, sel et poivre.",
      "Chauffer la plancha très fort.",
      "Cuire les gambas 2 à 3 minutes par face.",
      "Parsemer de persil et servir avec du riz ou une salade.",
    ],
  },
  "sardines-grillees": {
    servings: 4,
    ingredients: [
      { name: "sardines préparées", quantity: 12, unit: "" },
      { name: "citron", quantity: 1, unit: "" },
      { name: "salade verte", quantity: 1, unit: "", scalable: false },
      { name: "tomates", quantity: 2, unit: "" },
      { name: "huile d'olive", quantity: 2, unit: "c. à soupe" },
      { name: "vinaigre", quantity: 1, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Sécher les sardines et les badigeonner légèrement d'huile.",
      "Les griller 3 à 4 minutes par face.",
      "Préparer la salade avec tomates, vinaigre et huile.",
      "Servir les sardines avec le citron et la salade.",
    ],
  },
  "fish-and-chips": {
    servings: 4,
    ingredients: [
      { name: "filets de poisson blanc", quantity: 600, unit: "g" },
      { name: "pommes de terre", quantity: 800, unit: "g" },
      { name: "farine", quantity: 100, unit: "g" },
      { name: "œuf", quantity: 1, unit: "" },
      { name: "bière ou d'eau gazeuse", quantity: 12, unit: "cl" },
      { name: "paprika", quantity: 1, unit: "c. à café" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Préchauffer le four à 220 °C. Couper les pommes de terre en frites, mélanger avec un peu d'huile et cuire 30 à 35 minutes.",
      "Mélanger farine, paprika, œuf et bière pour obtenir une pâte épaisse.",
      "Tremper le poisson dans la pâte puis cuire à la poêle dans un fond d'huile jusqu'à ce qu'il soit doré et bien cuit.",
      "Servir avec les frites et du citron.",
    ],
  },
  "pates-champignons": {
    servings: 4,
    ingredients: [
      { name: "pâtes", quantity: 400, unit: "g" },
      { name: "champignons", quantity: 400, unit: "g" },
      { name: "échalote", quantity: 1, unit: "" },
      { name: "crème", quantity: 20, unit: "cl" },
      { name: "parmesan", quantity: 40, unit: "g" },
      { name: "huile d'olive", quantity: 1, unit: "c. à soupe" },
      { name: "gousse d'ail", quantity: 1, unit: "" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Cuire les pâtes.",
      "Faire revenir échalote, ail et champignons dans l'huile jusqu'à évaporation de l'eau.",
      "Ajouter la crème et le parmesan. Poivrer.",
      "Ajouter les pâtes avec un peu d'eau de cuisson et mélanger.",
    ],
  },
  "pates-pesto": {
    servings: 4,
    ingredients: [
      { name: "pâtes", quantity: 400, unit: "g" },
      { name: "pesto", quantity: 150, unit: "g" },
      { name: "tomates cerises", quantity: 300, unit: "g" },
      { name: "parmesan", quantity: 80, unit: "g" },
      { name: "huile d'olive", quantity: 1, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Cuire les pâtes.",
      "Couper les tomates cerises en deux et les faire revenir 3 minutes dans l'huile.",
      "Mélanger les pâtes chaudes avec le pesto et un peu d'eau de cuisson.",
      "Ajouter les tomates et le parmesan.",
    ],
  },
  "one-pot-pasta": {
    servings: 4,
    ingredients: [
      { name: "pâtes", quantity: 400, unit: "g" },
      { name: "tomates concassées", quantity: 400, unit: "g" },
      { name: "courgette", quantity: 1, unit: "" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "gousses d'ail", quantity: 2, unit: "" },
      { name: "bouillon de légumes", quantity: 700, unit: "ml" },
      { name: "parmesan", quantity: 50, unit: "g" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "basilic, sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Mettre dans une grande casserole pâtes, tomates, courgette, oignon, ail et bouillon.",
      "Porter à ébullition puis cuire 10 à 12 minutes en remuant souvent.",
      "Quand les pâtes sont cuites et la sauce épaissie, ajouter parmesan et basilic.",
      "Rectifier l'assaisonnement et servir.",
    ],
  },
  "lasagnes": {
    servings: 4,
    ingredients: [
      { name: "feuilles de lasagnes", quantity: 12, unit: "" },
      { name: "bœuf haché", quantity: 500, unit: "g" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "passata de tomate", quantity: 700, unit: "g" },
      { name: "béchamel", quantity: 50, unit: "cl" },
      { name: "fromage râpé", quantity: 100, unit: "g" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "sel, poivre et origan", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Faire revenir l'oignon puis le bœuf. Ajouter la tomate, l'origan, sel et poivre et mijoter 15 minutes.",
      "Dans un plat, alterner sauce, feuilles de lasagnes et béchamel.",
      "Terminer par béchamel et fromage.",
      "Cuire à 180 °C environ 40 minutes.",
    ],
  },
  "gratin-pates": {
    servings: 4,
    ingredients: [
      { name: "pâtes", quantity: 400, unit: "g" },
      { name: "jambon en dés", quantity: 200, unit: "g" },
      { name: "crème", quantity: 40, unit: "cl" },
      { name: "fromage râpé", quantity: 150, unit: "g" },
      { name: "moutarde", quantity: 1, unit: "c. à café" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Cuire les pâtes al dente.",
      "Mélanger crème, moutarde, sel et poivre.",
      "Mélanger pâtes, jambon et sauce puis mettre dans un plat.",
      "Couvrir de fromage et gratiner à 200 °C 15 à 20 minutes.",
    ],
  },
  "pates-burrata": {
    servings: 4,
    ingredients: [
      { name: "pâtes", quantity: 400, unit: "g" },
      { name: "tomates cerises", quantity: 500, unit: "g" },
      { name: "gousses d'ail", quantity: 2, unit: "" },
      { name: "boules de burrata", quantity: 2, unit: "" },
      { name: "huile d'olive", quantity: 2, unit: "c. à soupe" },
      { name: "origan", quantity: 1, unit: "c. à café" },
      { name: "basilic, sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Cuire les pâtes.",
      "Faire revenir les tomates avec l'ail, l'huile et l'origan jusqu'à ce qu'elles éclatent.",
      "Ajouter les pâtes avec un peu d'eau de cuisson et mélanger.",
      "Répartir dans les assiettes et déposer la burrata dessus.",
    ],
  },
  "riz-saute-legumes-oeufs": {
    servings: 4,
    ingredients: [
      { name: "riz déjà cuit", quantity: 300, unit: "g" },
      { name: "œufs", quantity: 4, unit: "" },
      { name: "carottes", quantity: 2, unit: "" },
      { name: "poivron", quantity: 1, unit: "" },
      { name: "petits pois", quantity: 150, unit: "g" },
      { name: "sauce soja", quantity: 2, unit: "c. à soupe" },
      { name: "huile de sésame", quantity: 1, unit: "c. à soupe" },
      { name: "huile neutre", quantity: 1, unit: "c. à soupe" },
    ],
    steps: [
      "Cuire le riz à l'avance et le laisser refroidir.",
      "Faire sauter carottes, poivron et petits pois dans l'huile.",
      "Repousser les légumes sur le côté, brouiller les œufs puis mélanger.",
      "Ajouter le riz, la sauce soja et l'huile de sésame. Faire sauter 4 à 5 minutes.",
    ],
  },
  "risotto-champignons": {
    servings: 4,
    ingredients: [
      { name: "riz arborio", quantity: 300, unit: "g" },
      { name: "champignons", quantity: 400, unit: "g" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "bouillon de légumes", quantity: 1, unit: "l" },
      { name: "vin blanc", quantity: 10, unit: "cl" },
      { name: "parmesan", quantity: 40, unit: "g" },
      { name: "beurre", quantity: 30, unit: "g" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
    ],
    steps: [
      "Faire revenir l'oignon et les champignons dans l'huile.",
      "Ajouter le riz et le nacrer 2 minutes.",
      "Verser le vin puis ajouter le bouillon progressivement en remuant pendant environ 18 minutes.",
      "Hors du feu, incorporer beurre et parmesan.",
    ],
  },
  "riz-cantonais": {
    servings: 4,
    ingredients: [
      { name: "riz", quantity: 300, unit: "g" },
      { name: "œufs", quantity: 3, unit: "" },
      { name: "petits pois", quantity: 150, unit: "g" },
      { name: "dés de jambon", quantity: 150, unit: "g" },
      { name: "carottes", quantity: 2, unit: "" },
      { name: "sauce soja", quantity: 2, unit: "c. à soupe" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
    ],
    steps: [
      "Cuire le riz et le laisser refroidir.",
      "Faire revenir carottes, petits pois et jambon.",
      "Ajouter les œufs battus et brouiller rapidement.",
      "Ajouter le riz et la sauce soja. Faire sauter quelques minutes.",
    ],
  },
  "buddha-bowl": {
    servings: 4,
    ingredients: [
      { name: "quinoa", quantity: 250, unit: "g" },
      { name: "avocat", quantity: 1, unit: "" },
      { name: "carottes", quantity: 2, unit: "" },
      { name: "concombre", quantity: 1, unit: "" },
      { name: "pois chiches cuits", quantity: 150, unit: "g" },
      { name: "feta", quantity: 100, unit: "g" },
      { name: "graines", quantity: 2, unit: "c. à soupe" },
      { name: "citron", quantity: 1, unit: "" },
      { name: "huile d'olive", quantity: 2, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Cuire le quinoa puis le laisser tiédir.",
      "Préparer carottes, concombre et avocat.",
      "Répartir quinoa, pois chiches et légumes dans les bols.",
      "Ajouter feta et graines. Assaisonner avec citron, huile, sel et poivre.",
    ],
  },
  "riz-poulet-thermomix": {
    servings: 4,
    ingredients: [
      { name: "poulet", quantity: 500, unit: "g" },
      { name: "riz", quantity: 250, unit: "g" },
      { name: "courgette", quantity: 1, unit: "" },
      { name: "carottes", quantity: 2, unit: "" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "bouillon", quantity: 600, unit: "ml" },
      { name: "sauce soja", quantity: 2, unit: "c. à soupe" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Émincer l'oignon et couper les légumes. Les faire revenir dans le Thermomix avec l'huile quelques minutes.",
      "Ajouter le poulet en morceaux et cuire quelques minutes en sens inverse.",
      "Ajouter riz, bouillon et sauce soja.",
      "Cuire jusqu'à ce que le riz soit tendre, en utilisant le mode/sens inverse adapté à votre Thermomix.",
    ],
  },
  "shakshuka": {
    servings: 4,
    ingredients: [
      { name: "œufs", quantity: 6, unit: "" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "poivrons", quantity: 2, unit: "" },
      { name: "tomates concassées", quantity: 800, unit: "g" },
      { name: "gousses d'ail", quantity: 2, unit: "" },
      { name: "cumin", quantity: 1, unit: "c. à café" },
      { name: "paprika", quantity: 1, unit: "c. à café" },
      { name: "huile d'olive", quantity: 2, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Faire revenir oignon et poivrons dans l'huile 8 minutes.",
      "Ajouter ail, cumin et paprika puis cuire 1 minute.",
      "Ajouter les tomates et mijoter 10 minutes.",
      "Creuser 6 petits puits, casser les œufs et couvrir. Cuire jusqu'à ce que les blancs soient pris.",
    ],
  },
  "oeufs-cocotte": {
    servings: 4,
    ingredients: [
      { name: "œufs", quantity: 8, unit: "" },
      { name: "épinards", quantity: 400, unit: "g" },
      { name: "crème", quantity: 20, unit: "cl" },
      { name: "parmesan", quantity: 40, unit: "g" },
      { name: "échalote", quantity: 1, unit: "" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Faire tomber les épinards avec l'échalote dans l'huile.",
      "Répartir les épinards dans 4 ramequins et ajouter une cuillère de crème.",
      "Casser 2 œufs dans chaque ramequin. Saler, poivrer et parsemer de parmesan.",
      "Cuire au bain-marie à 180 °C environ 10 à 12 minutes.",
    ],
  },
  "frittata-courgette": {
    servings: 4,
    ingredients: [
      { name: "œufs", quantity: 8, unit: "" },
      { name: "courgettes", quantity: 2, unit: "" },
      { name: "feta", quantity: 150, unit: "g" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "huile d'olive", quantity: 2, unit: "c. à soupe" },
      { name: "origan", quantity: 1, unit: "c. à café" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Faire revenir oignon et courgettes en fines rondelles dans l'huile.",
      "Battre les œufs avec l'origan, sel et poivre.",
      "Verser sur les légumes et répartir la feta émiettée.",
      "Cuire à feu doux puis terminer au four à 180 °C jusqu'à ce que les œufs soient pris.",
    ],
  },
  "gratin-courgettes-chevre": {
    servings: 4,
    ingredients: [
      { name: "courgettes", quantity: 4, unit: "" },
      { name: "chèvre", quantity: 200, unit: "g" },
      { name: "crème", quantity: 20, unit: "cl" },
      { name: "gousse d'ail", quantity: 1, unit: "" },
      { name: "chapelure", quantity: 50, unit: "g" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Préchauffer le four à 190 °C.",
      "Couper les courgettes en rondelles et les faire revenir 5 minutes avec l'ail.",
      "Mettre dans un plat, ajouter la crème et le chèvre en morceaux.",
      "Parsemer de chapelure et cuire 25 à 30 minutes.",
    ],
  },
  "curry-legumes-coco": {
    servings: 4,
    ingredients: [
      { name: "courgette", quantity: 1, unit: "" },
      { name: "carottes", quantity: 2, unit: "" },
      { name: "poivron", quantity: 1, unit: "" },
      { name: "pois chiches cuits", quantity: 200, unit: "g" },
      { name: "lait de coco", quantity: 400, unit: "ml" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "pâte de curry doux", quantity: 2, unit: "c. à soupe" },
      { name: "riz", quantity: 250, unit: "g" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
    ],
    steps: [
      "Cuire le riz.",
      "Faire revenir l'oignon et les légumes dans l'huile.",
      "Ajouter la pâte de curry et les pois chiches.",
      "Verser le lait de coco et mijoter 15 minutes. Servir avec le riz.",
    ],
  },
  "chili-vegetarien": {
    servings: 4,
    ingredients: [
      { name: "haricots rouges", quantity: 400, unit: "g" },
      { name: "maïs", quantity: 200, unit: "g" },
      { name: "tomates concassées", quantity: 400, unit: "g" },
      { name: "poivron", quantity: 1, unit: "" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "cumin", quantity: 1, unit: "c. à café" },
      { name: "paprika", quantity: 1, unit: "c. à café" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "riz", quantity: 250, unit: "g" },
    ],
    steps: [
      "Cuire le riz.",
      "Faire revenir oignon et poivron dans l'huile.",
      "Ajouter tomates, haricots, maïs et épices.",
      "Mijoter 20 minutes et servir avec le riz.",
    ],
  },
  "ratatouille": {
    servings: 4,
    ingredients: [
      { name: "courgettes", quantity: 2, unit: "" },
      { name: "aubergine", quantity: 1, unit: "" },
      { name: "poivron", quantity: 1, unit: "" },
      { name: "tomates", quantity: 4, unit: "" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "gousses d'ail", quantity: 2, unit: "" },
      { name: "huile d'olive", quantity: 3, unit: "c. à soupe" },
      { name: "riz", quantity: 250, unit: "g" },
      { name: "herbes de provence, sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Faire revenir l'oignon et le poivron dans l'huile.",
      "Ajouter aubergine puis courgettes.",
      "Ajouter tomates, ail et herbes. Mijoter 25 minutes.",
      "Cuire le riz et servir avec la ratatouille.",
    ],
  },
  "boulettes-veg-thermomix": {
    servings: 4,
    ingredients: [
      { name: "lentilles cuites", quantity: 250, unit: "g" },
      { name: "carotte", quantity: 1, unit: "" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "flocons d'avoine", quantity: 80, unit: "g" },
      { name: "œuf", quantity: 1, unit: "" },
      { name: "cumin", quantity: 1, unit: "c. à café" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Mixer lentilles, carotte et oignon dans le Thermomix sans réduire en purée trop fine.",
      "Ajouter avoine, œuf et épices puis mélanger.",
      "Former des boulettes et les placer sur une plaque.",
      "Cuire à 190 °C environ 20 minutes en les retournant à mi-cuisson.",
    ],
  },
  "tofu-saute": {
    servings: 4,
    ingredients: [
      { name: "tofu ferme", quantity: 400, unit: "g" },
      { name: "poivron", quantity: 1, unit: "" },
      { name: "carottes", quantity: 2, unit: "" },
      { name: "brocoli", quantity: 1, unit: "" },
      { name: "gousses d'ail", quantity: 2, unit: "" },
      { name: "sauce soja", quantity: 3, unit: "c. à soupe" },
      { name: "huile de sésame", quantity: 1, unit: "c. à soupe" },
      { name: "riz", quantity: 250, unit: "g" },
    ],
    steps: [
      "Cuire le riz.",
      "Presser le tofu puis le couper en dés. Le faire dorer dans l'huile.",
      "Ajouter les légumes et l'ail et faire sauter 6 à 8 minutes.",
      "Ajouter la sauce soja et l'huile de sésame. Servir avec le riz.",
    ],
  },
  "chili-patate-douce": {
    servings: 4,
    ingredients: [
      { name: "patates douces", quantity: 2, unit: "" },
      { name: "haricots noirs", quantity: 400, unit: "g" },
      { name: "tomates concassées", quantity: 400, unit: "g" },
      { name: "poivron", quantity: 1, unit: "" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "cumin", quantity: 1, unit: "c. à café" },
      { name: "paprika", quantity: 1, unit: "c. à café" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
    ],
    steps: [
      "Faire revenir oignon et poivron dans l'huile.",
      "Ajouter les patates douces en dés et les épices.",
      "Ajouter tomates et un petit verre d'eau. Couvrir et cuire 15 minutes.",
      "Ajouter les haricots et poursuivre 8 à 10 minutes.",
    ],
  },
  "gratin-chou-fleur": {
    servings: 4,
    ingredients: [
      { name: "gros chou-fleur", quantity: 1, unit: "" },
      { name: "béchamel", quantity: 40, unit: "cl" },
      { name: "fromage râpé", quantity: 100, unit: "g" },
      { name: "beurre", quantity: 20, unit: "g" },
      { name: "sel, poivre et muscade", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Cuire le chou-fleur en bouquets 8 à 10 minutes à l'eau ou à la vapeur.",
      "Égoutter soigneusement et mettre dans un plat beurré.",
      "Couvrir de béchamel, fromage, sel, poivre et muscade.",
      "Gratiner à 200 °C 20 minutes.",
    ],
  },
  "tartiflette": {
    servings: 4,
    ingredients: [
      { name: "pommes de terre", quantity: 1.2, unit: "kg" },
      { name: "lardons", quantity: 200, unit: "g" },
      { name: "reblochon", quantity: 1, unit: "" },
      { name: "oignons", quantity: 2, unit: "" },
      { name: "crème", quantity: 10, unit: "cl" },
      { name: "poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Cuire les pommes de terre puis les couper en morceaux.",
      "Faire revenir oignons et lardons.",
      "Mélanger avec les pommes de terre et la crème dans un plat.",
      "Couper le reblochon en deux dans l'épaisseur et le poser croûte vers le haut. Cuire à 200 °C 20 minutes.",
    ],
  },
  "parmentier-canard": {
    servings: 4,
    ingredients: [
      { name: "cuisses de canard confites", quantity: 4, unit: "" },
      { name: "pommes de terre", quantity: 1, unit: "kg" },
      { name: "lait", quantity: 15, unit: "cl" },
      { name: "beurre", quantity: 40, unit: "g" },
      { name: "échalote", quantity: 1, unit: "" },
      { name: "chapelure", quantity: 50, unit: "g" },
      { name: "poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Effilocher le canard et retirer l'excès de graisse.",
      "Préparer une purée avec les pommes de terre, lait et beurre.",
      "Faire revenir l'échalote et mélanger au canard.",
      "Mettre le canard dans un plat, couvrir de purée, parsemer de chapelure et gratiner 20 minutes à 200 °C.",
    ],
  },
  "gratin-legumes-airfryer": {
    servings: 4,
    ingredients: [
      { name: "courgettes", quantity: 2, unit: "" },
      { name: "carottes", quantity: 2, unit: "" },
      { name: "poivron", quantity: 1, unit: "" },
      { name: "pommes de terre", quantity: 400, unit: "g" },
      { name: "fromage râpé", quantity: 100, unit: "g" },
      { name: "huile", quantity: 2, unit: "c. à soupe" },
      { name: "herbes de Provence", quantity: 1, unit: "c. à café" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Couper les légumes en petits morceaux.",
      "Mélanger avec huile, herbes, sel et poivre.",
      "Cuire dans l'Airfryer à 190 °C environ 20 minutes en secouant à mi-cuisson.",
      "Ajouter le fromage et cuire encore 3 à 5 minutes.",
    ],
  },
  "poelee-legumes-oeuf": {
    servings: 4,
    ingredients: [
      { name: "courgettes", quantity: 2, unit: "" },
      { name: "poivrons", quantity: 2, unit: "" },
      { name: "champignons", quantity: 250, unit: "g" },
      { name: "œufs", quantity: 4, unit: "" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "huile", quantity: 2, unit: "c. à soupe" },
      { name: "herbes de Provence", quantity: 1, unit: "c. à café" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Faire revenir l'oignon et les légumes dans l'huile 10 minutes.",
      "Assaisonner et répartir les légumes dans la poêle.",
      "Casser les œufs dessus, couvrir et cuire jusqu'à ce que les blancs soient pris.",
      "Servir immédiatement.",
    ],
  },
  "polenta-cremeuse": {
    servings: 4,
    ingredients: [
      { name: "polenta", quantity: 200, unit: "g" },
      { name: "lait ou bouillon", quantity: 80, unit: "cl" },
      { name: "parmesan", quantity: 50, unit: "g" },
      { name: "courgette", quantity: 1, unit: "" },
      { name: "poivron", quantity: 1, unit: "" },
      { name: "tomates cerises", quantity: 200, unit: "g" },
      { name: "huile d'olive", quantity: 2, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Faire cuire la polenta dans le liquide selon les indications du paquet.",
      "Ajouter parmesan et assaisonner.",
      "Faire rôtir les légumes à la poêle avec l'huile.",
      "Servir les légumes sur la polenta crémeuse.",
    ],
  },
  "pizza-veggie": {
    servings: 4,
    ingredients: [
      { name: "pâte à pizza", quantity: 1, unit: "", scalable: false },
      { name: "coulis de tomate", quantity: 200, unit: "g" },
      { name: "mozzarella", quantity: 200, unit: "g" },
      { name: "courgette", quantity: 1, unit: "" },
      { name: "poivron", quantity: 1, unit: "" },
      { name: "champignons", quantity: 150, unit: "g" },
      { name: "origan", quantity: 1, unit: "c. à café" },
    ],
    steps: [
      "Préchauffer le four à 240 °C.",
      "Étaler la pâte et répartir le coulis.",
      "Ajouter mozzarella et légumes finement tranchés.",
      "Cuire 10 à 12 minutes et ajouter un filet d'huile d'olive à la sortie du four.",
    ],
  },
  "tarte-legumes": {
    servings: 4,
    ingredients: [
      { name: "pâte feuilletée", quantity: 1, unit: "", scalable: false },
      { name: "courgette", quantity: 1, unit: "" },
      { name: "tomates", quantity: 2, unit: "" },
      { name: "poivron", quantity: 1, unit: "" },
      { name: "fromage de chèvre", quantity: 100, unit: "g" },
      { name: "huile d'olive", quantity: 1, unit: "c. à soupe" },
      { name: "herbes de Provence", quantity: 1, unit: "c. à café" },
    ],
    steps: [
      "Préchauffer le four à 200 °C.",
      "Dérouler la pâte sur une plaque et la piquer.",
      "Répartir les légumes finement tranchés et le chèvre.",
      "Arroser d'huile, ajouter les herbes et cuire 25 minutes.",
    ],
  },
  "quiche-legumes": {
    servings: 4,
    ingredients: [
      { name: "pâte brisée", quantity: 1, unit: "", scalable: false },
      { name: "courgette", quantity: 1, unit: "" },
      { name: "poivron", quantity: 1, unit: "" },
      { name: "tomates cerises", quantity: 150, unit: "g" },
      { name: "œufs", quantity: 3, unit: "" },
      { name: "crème", quantity: 20, unit: "cl" },
      { name: "fromage râpé", quantity: 100, unit: "g" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Préchauffer le four à 180 °C et foncer le moule.",
      "Faire revenir les légumes 5 minutes.",
      "Battre œufs et crème, saler et poivrer.",
      "Répartir légumes et fromage sur la pâte, verser l'appareil et cuire 35 minutes.",
    ],
  },
  "soupe-legumes": {
    servings: 4,
    ingredients: [
      { name: "carottes", quantity: 3, unit: "" },
      { name: "pommes de terre", quantity: 2, unit: "" },
      { name: "courgette", quantity: 1, unit: "" },
      { name: "poireau", quantity: 1, unit: "" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "bouillon de légumes", quantity: 1, unit: "l" },
      { name: "pain", quantity: 8, unit: "tranches" },
      { name: "fromage râpé", quantity: 80, unit: "g" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
    ],
    steps: [
      "Faire revenir l'oignon et le poireau dans l'huile.",
      "Ajouter les légumes coupés et le bouillon.",
      "Cuire 25 minutes puis mixer.",
      "Faire griller le pain, parsemer de fromage et servir avec la soupe.",
    ],
  },
  "soupe-potiron-thermomix": {
    servings: 4,
    ingredients: [
      { name: "potiron", quantity: 800, unit: "g" },
      { name: "pommes de terre", quantity: 2, unit: "" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "bouillon de légumes", quantity: 700, unit: "ml" },
      { name: "crème", quantity: 10, unit: "cl" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Faire revenir l'oignon dans le Thermomix avec l'huile.",
      "Ajouter potiron, pommes de terre et bouillon.",
      "Cuire environ 20 minutes selon le programme adapté.",
      "Mixer jusqu'à obtenir un velouté puis ajouter la crème.",
    ],
  },
  "minestrone": {
    servings: 4,
    ingredients: [
      { name: "courgette", quantity: 1, unit: "" },
      { name: "carottes", quantity: 2, unit: "" },
      { name: "branche de céleri", quantity: 1, unit: "" },
      { name: "poireau", quantity: 1, unit: "" },
      { name: "tomates concassées", quantity: 400, unit: "g" },
      { name: "petites pâtes", quantity: 100, unit: "g" },
      { name: "bouillon", quantity: 1.2, unit: "l" },
      { name: "haricots blancs", quantity: 150, unit: "g" },
      { name: "huile", quantity: 2, unit: "c. à soupe" },
      { name: "parmesan", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Faire revenir les légumes coupés dans l'huile.",
      "Ajouter tomates et bouillon puis cuire 15 minutes.",
      "Ajouter les pâtes et les haricots et cuire jusqu'à ce que les pâtes soient tendres.",
      "Servir avec du parmesan.",
    ],
  },
  "soupe-thai": {
    servings: 4,
    ingredients: [
      { name: "lait de coco", quantity: 400, unit: "ml" },
      { name: "bouillon", quantity: 700, unit: "ml" },
      { name: "carottes", quantity: 2, unit: "" },
      { name: "courgette", quantity: 1, unit: "" },
      { name: "champignons", quantity: 150, unit: "g" },
      { name: "nouilles de riz", quantity: 150, unit: "g" },
      { name: "pâte de curry rouge doux", quantity: 1, unit: "c. à soupe" },
      { name: "citron vert", quantity: 1, unit: "" },
      { name: "sauce soja", quantity: 1, unit: "c. à soupe" },
    ],
    steps: [
      "Faire chauffer le bouillon avec le lait de coco et la pâte de curry.",
      "Ajouter carottes, courgette et champignons et cuire 8 minutes.",
      "Ajouter les nouilles et cuire selon leur temps.",
      "Ajouter sauce soja et jus de citron vert avant de servir.",
    ],
  },
  "veloute-carotte": {
    servings: 4,
    ingredients: [
      { name: "carottes", quantity: 700, unit: "g" },
      { name: "pommes de terre", quantity: 2, unit: "" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "lait de coco", quantity: 400, unit: "ml" },
      { name: "bouillon", quantity: 600, unit: "ml" },
      { name: "curry", quantity: 1, unit: "c. à café" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Faire revenir l'oignon dans l'huile.",
      "Ajouter carottes et pommes de terre en morceaux, curry et bouillon.",
      "Cuire 25 minutes.",
      "Mixer avec le lait de coco et rectifier l'assaisonnement.",
    ],
  },
  "salade-cesar": {
    servings: 4,
    ingredients: [
      { name: "grosses salades romaines", quantity: 2, unit: "" },
      { name: "poulet", quantity: 500, unit: "g" },
      { name: "parmesan", quantity: 80, unit: "g" },
      { name: "croûtons", quantity: 100, unit: "g" },
      { name: "yaourt grec", quantity: 1, unit: "" },
      { name: "moutarde", quantity: 1, unit: "c. à café" },
      { name: "citron", quantity: 0.5, unit: "" },
      { name: "huile d'olive", quantity: 1, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Faire dorer le poulet en morceaux dans l'huile.",
      "Mélanger yaourt, moutarde, citron, sel et poivre pour la sauce.",
      "Laver et couper la salade.",
      "Ajouter poulet, croûtons et parmesan puis napper de sauce.",
    ],
  },
  "salade-pates-mozza": {
    servings: 4,
    ingredients: [
      { name: "pâtes", quantity: 300, unit: "g" },
      { name: "tomates cerises", quantity: 250, unit: "g" },
      { name: "boules de mozzarella", quantity: 2, unit: "" },
      { name: "roquette", quantity: 100, unit: "g" },
      { name: "huile d'olive", quantity: 2, unit: "c. à soupe" },
      { name: "vinaigre balsamique", quantity: 1, unit: "c. à soupe" },
      { name: "basilic, sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Cuire les pâtes, les refroidir sous l'eau et les égoutter.",
      "Couper tomates et mozzarella.",
      "Mélanger huile, vinaigre, sel et poivre.",
      "Assembler pâtes, légumes, mozzarella et roquette.",
    ],
  },
  "salade-nicoise": {
    servings: 4,
    ingredients: [
      { name: "œufs", quantity: 4, unit: "" },
      { name: "pommes de terre", quantity: 400, unit: "g" },
      { name: "haricots verts", quantity: 250, unit: "g" },
      { name: "tomates", quantity: 2, unit: "" },
      { name: "thon", quantity: 1, unit: "boîte" },
      { name: "olives noires", quantity: 80, unit: "g" },
      { name: "salade", quantity: 1, unit: "", scalable: false },
      { name: "huile d'olive", quantity: 2, unit: "c. à soupe" },
      { name: "vinaigre", quantity: 1, unit: "c. à soupe" },
    ],
    steps: [
      "Cuire les pommes de terre, les haricots et les œufs séparément.",
      "Couper tomates et pommes de terre.",
      "Assembler salade, légumes, thon, œufs et olives.",
      "Assaisonner avec huile, vinaigre, sel et poivre.",
    ],
  },
  "salade-quinoa-feta": {
    servings: 4,
    ingredients: [
      { name: "quinoa", quantity: 250, unit: "g" },
      { name: "concombre", quantity: 1, unit: "" },
      { name: "tomates cerises", quantity: 250, unit: "g" },
      { name: "feta", quantity: 150, unit: "g" },
      { name: "oignon rouge", quantity: 0.5, unit: "" },
      { name: "citron", quantity: 1, unit: "" },
      { name: "huile d'olive", quantity: 2, unit: "c. à soupe" },
      { name: "persil, sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Cuire le quinoa puis le laisser refroidir.",
      "Couper concombre, tomates et oignon.",
      "Mélanger tous les ingrédients avec feta et persil.",
      "Assaisonner avec citron, huile, sel et poivre.",
    ],
  },
  "poke-bowl-saumon": {
    servings: 4,
    ingredients: [
      { name: "saumon frais", quantity: 400, unit: "g" },
      { name: "riz", quantity: 250, unit: "g" },
      { name: "avocat", quantity: 1, unit: "" },
      { name: "concombre", quantity: 1, unit: "" },
      { name: "carotte", quantity: 1, unit: "" },
      { name: "edamame", quantity: 100, unit: "g" },
      { name: "sauce soja", quantity: 2, unit: "c. à soupe" },
      { name: "huile de sésame", quantity: 1, unit: "c. à café" },
      { name: "graines de sésame", quantity: 1, unit: "c. à soupe" },
    ],
    steps: [
      "Cuire le riz et le laisser tiédir.",
      "Couper le saumon en dés et l'assaisonner avec soja et huile de sésame.",
      "Préparer avocat, concombre et carotte.",
      "Répartir le riz dans les bols, ajouter saumon, légumes et edamame. Parsemer de sésame.",
    ],
  },
  "salade-lentilles": {
    servings: 4,
    ingredients: [
      { name: "lentilles vertes", quantity: 250, unit: "g" },
      { name: "carottes", quantity: 2, unit: "" },
      { name: "concombre", quantity: 0.5, unit: "" },
      { name: "tomates cerises", quantity: 150, unit: "g" },
      { name: "feta", quantity: 100, unit: "g" },
      { name: "moutarde", quantity: 1, unit: "c. à soupe" },
      { name: "huile", quantity: 2, unit: "c. à soupe" },
      { name: "vinaigre", quantity: 1, unit: "c. à soupe" },
    ],
    steps: [
      "Cuire les lentilles puis les laisser refroidir.",
      "Couper les légumes et la feta.",
      "Mélanger moutarde, huile et vinaigre.",
      "Assembler le tout et assaisonner.",
    ],
  },
  "quesadillas": {
    servings: 4,
    ingredients: [
      { name: "tortillas", quantity: 8, unit: "" },
      { name: "poulet", quantity: 400, unit: "g" },
      { name: "cheddar râpé", quantity: 150, unit: "g" },
      { name: "poivron", quantity: 1, unit: "" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "paprika", quantity: 1, unit: "c. à café" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
    ],
    steps: [
      "Faire revenir oignon, poivron et poulet en petits morceaux avec paprika.",
      "Déposer la garniture et le fromage sur une tortilla puis couvrir d'une seconde.",
      "Cuire à la poêle 2 à 3 minutes par face.",
      "Couper en parts et servir.",
    ],
  },
  "tartines-avocat-oeuf": {
    servings: 4,
    ingredients: [
      { name: "pain", quantity: 8, unit: "tranches" },
      { name: "avocats", quantity: 2, unit: "" },
      { name: "œufs", quantity: 4, unit: "" },
      { name: "citron", quantity: 1, unit: "" },
      { name: "tomates cerises", quantity: 100, unit: "g" },
      { name: "huile d'olive", quantity: 1, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Griller le pain.",
      "Cuire les œufs mollets ou au plat.",
      "Écraser les avocats avec citron, sel et poivre.",
      "Tartiner le pain, ajouter avocat, œuf et tomates.",
    ],
  },
  "bagels-saumon": {
    servings: 4,
    ingredients: [
      { name: "bagels", quantity: 4, unit: "" },
      { name: "saumon fumé", quantity: 200, unit: "g" },
      { name: "fromage frais", quantity: 150, unit: "g" },
      { name: "concombre", quantity: 0.5, unit: "" },
      { name: "citron", quantity: 1, unit: "" },
      { name: "roquette", quantity: 1, unit: "poignée" },
      { name: "poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Couper les bagels et les toaster légèrement.",
      "Tartiner de fromage frais.",
      "Ajouter saumon, concombre et roquette.",
      "Terminer avec citron et poivre.",
    ],
  },
  "croque-veggie": {
    servings: 4,
    ingredients: [
      { name: "pain de mie", quantity: 8, unit: "tranches" },
      { name: "tomates", quantity: 2, unit: "" },
      { name: "boule de mozzarella", quantity: 1, unit: "" },
      { name: "pesto", quantity: 80, unit: "g" },
      { name: "fromage râpé", quantity: 50, unit: "g" },
      { name: "salade verte", quantity: 1, unit: "", scalable: false },
    ],
    steps: [
      "Tartiner les tranches de pesto.",
      "Ajouter tomates et mozzarella puis refermer.",
      "Parsemer légèrement de fromage et cuire au four à 200 °C 10 minutes.",
      "Servir avec la salade.",
    ],
  },
  "galettes-completes": {
    servings: 4,
    ingredients: [
      { name: "galettes de sarrasin", quantity: 8, unit: "" },
      { name: "œufs", quantity: 8, unit: "" },
      { name: "jambon", quantity: 8, unit: "tranches" },
      { name: "fromage râpé", quantity: 150, unit: "g" },
      { name: "beurre", quantity: 30, unit: "g" },
      { name: "poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Chauffer une galette dans une poêle beurrée.",
      "Déposer jambon, fromage et un œuf au centre.",
      "Poivrer et rabattre les bords quand le blanc est cuit.",
      "Répéter pour les autres galettes.",
    ],
  },
  "crepes-salees-champi": {
    servings: 4,
    ingredients: [
      { name: "crêpes salées", quantity: 8, unit: "" },
      { name: "champignons", quantity: 400, unit: "g" },
      { name: "beurre", quantity: 30, unit: "g" },
      { name: "farine", quantity: 30, unit: "g" },
      { name: "lait", quantity: 40, unit: "cl" },
      { name: "fromage râpé", quantity: 100, unit: "g" },
      { name: "échalote", quantity: 1, unit: "" },
      { name: "sel, poivre et muscade", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Faire revenir échalote et champignons dans le beurre.",
      "Préparer une béchamel avec beurre, farine et lait. Assaisonner de muscade.",
      "Mélanger les champignons avec la béchamel.",
      "Garnir les crêpes, ajouter fromage et gratiner 10 minutes à 200 °C.",
    ],
  },
  "burritos": {
    servings: 4,
    ingredients: [
      { name: "tortillas", quantity: 8, unit: "" },
      { name: "haricots rouges", quantity: 400, unit: "g" },
      { name: "riz", quantity: 250, unit: "g" },
      { name: "maïs", quantity: 150, unit: "g" },
      { name: "poivron", quantity: 1, unit: "" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "cheddar", quantity: 100, unit: "g" },
      { name: "cumin", quantity: 1, unit: "c. à café" },
      { name: "paprika", quantity: 1, unit: "c. à café" },
    ],
    steps: [
      "Cuire le riz.",
      "Faire revenir oignon et poivron puis ajouter haricots, maïs et épices.",
      "Garnir les tortillas de riz, mélange de haricots et cheddar.",
      "Rouler les burritos et les réchauffer à la poêle ou au four quelques minutes.",
    ],
  },
  "pad-thai": {
    servings: 4,
    ingredients: [
      { name: "nouilles de riz", quantity: 250, unit: "g" },
      { name: "tofu ferme", quantity: 300, unit: "g" },
      { name: "œufs", quantity: 2, unit: "" },
      { name: "carottes", quantity: 2, unit: "" },
      { name: "poivron", quantity: 1, unit: "" },
      { name: "pousses de soja", quantity: 100, unit: "g" },
      { name: "sauce soja", quantity: 3, unit: "c. à soupe" },
      { name: "jus de citron vert", quantity: 1, unit: "c. à soupe" },
      { name: "beurre de cacahuète", quantity: 1, unit: "c. à soupe" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
    ],
    steps: [
      "Réhydrater les nouilles selon le paquet.",
      "Faire dorer le tofu dans l'huile.",
      "Ajouter les légumes puis les œufs et brouiller rapidement.",
      "Ajouter les nouilles, soja, citron vert et beurre de cacahuète. Mélanger 2 minutes.",
    ],
  },
  "couscous-legumes": {
    servings: 4,
    ingredients: [
      { name: "semoule", quantity: 250, unit: "g" },
      { name: "carottes", quantity: 2, unit: "" },
      { name: "courgettes", quantity: 2, unit: "" },
      { name: "poivron", quantity: 1, unit: "" },
      { name: "pois chiches", quantity: 200, unit: "g" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "bouillon", quantity: 500, unit: "ml" },
      { name: "cumin", quantity: 1, unit: "c. à café" },
      { name: "ras el-hanout", quantity: 1, unit: "c. à café" },
      { name: "huile", quantity: 2, unit: "c. à soupe" },
    ],
    steps: [
      "Faire revenir l'oignon et les légumes dans l'huile.",
      "Ajouter épices, pois chiches et bouillon.",
      "Mijoter 20 minutes.",
      "Préparer la semoule et servir avec les légumes et leur bouillon.",
    ],
  },
  "tajine-poulet": {
    servings: 4,
    ingredients: [
      { name: "poulet", quantity: 600, unit: "g" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "olives vertes", quantity: 150, unit: "g" },
      { name: "citrons confits", quantity: 2, unit: "" },
      { name: "carottes", quantity: 2, unit: "" },
      { name: "cumin", quantity: 1, unit: "c. à café" },
      { name: "curcuma", quantity: 1, unit: "c. à café" },
      { name: "huile", quantity: 2, unit: "c. à soupe" },
      { name: "semoule", quantity: 250, unit: "g" },
    ],
    steps: [
      "Faire dorer le poulet dans l'huile.",
      "Ajouter l'oignon et les carottes puis les épices.",
      "Couvrir d'un petit verre d'eau et mijoter 25 minutes.",
      "Ajouter olives et citron confit en morceaux sur les 10 dernières minutes. Servir avec la semoule.",
    ],
  },
  "gyoza-riz": {
    servings: 4,
    ingredients: [
      { name: "gyozas", quantity: 400, unit: "g" },
      { name: "riz", quantity: 250, unit: "g" },
      { name: "carotte", quantity: 1, unit: "" },
      { name: "concombre", quantity: 0.5, unit: "" },
      { name: "chou émincé", quantity: 150, unit: "g" },
      { name: "sauce soja", quantity: 2, unit: "c. à soupe" },
      { name: "huile de sésame", quantity: 1, unit: "c. à café" },
      { name: "huile neutre", quantity: 1, unit: "c. à soupe" },
    ],
    steps: [
      "Cuire le riz.",
      "Faire dorer les gyozas dans l'huile puis ajouter un petit fond d'eau et couvrir pour terminer la cuisson.",
      "Émincer les légumes.",
      "Servir gyozas et riz avec les légumes, sauce soja et huile de sésame.",
    ],
  },
  "nasi-goreng": {
    servings: 4,
    ingredients: [
      { name: "riz cuit froid", quantity: 300, unit: "g" },
      { name: "poulet", quantity: 300, unit: "g" },
      { name: "œufs", quantity: 2, unit: "" },
      { name: "carotte", quantity: 1, unit: "" },
      { name: "poivron", quantity: 0.5, unit: "" },
      { name: "gousses d'ail", quantity: 2, unit: "" },
      { name: "sauce soja", quantity: 3, unit: "c. à soupe" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "curry", quantity: 1, unit: "c. à café" },
    ],
    steps: [
      "Faire revenir le poulet dans l'huile.",
      "Ajouter carotte, poivron et ail.",
      "Ajouter les œufs et les brouiller.",
      "Ajouter le riz, le curry et la sauce soja. Faire sauter 4 à 5 minutes.",
    ],
  },
  "hot-dog-maison": {
    servings: 4,
    ingredients: [
      { name: "pains à hot-dog", quantity: 4, unit: "" },
      { name: "saucisses", quantity: 4, unit: "" },
      { name: "pommes de terre", quantity: 800, unit: "g" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "ketchup", quantity: 4, unit: "c. à soupe" },
      { name: "moutarde", quantity: 4, unit: "c. à soupe" },
      { name: "huile", quantity: 2, unit: "c. à soupe" },
    ],
    steps: [
      "Préchauffer le four à 220 °C et cuire les pommes de terre en quartiers avec l'huile 30 minutes.",
      "Cuire les saucisses à la poêle.",
      "Réchauffer les pains.",
      "Garnir de saucisse, oignon, ketchup et moutarde. Servir avec les potatoes.",
    ],
  },
  "burger-maison": {
    servings: 4,
    ingredients: [
      { name: "pains burger", quantity: 4, unit: "" },
      { name: "bœuf haché", quantity: 500, unit: "g" },
      { name: "cheddar", quantity: 4, unit: "tranches" },
      { name: "tomate", quantity: 1, unit: "" },
      { name: "salade", quantity: 0.5, unit: "", scalable: false },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "pommes de terre", quantity: 800, unit: "g" },
      { name: "huile", quantity: 2, unit: "c. à soupe" },
      { name: "ketchup et moutarde", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Former 4 steaks et les assaisonner.",
      "Cuire les potatoes au four à 220 °C environ 30 minutes.",
      "Cuire les steaks selon la cuisson souhaitée et ajouter le cheddar en fin de cuisson.",
      "Toaster les pains puis monter les burgers avec salade, tomate, oignon et sauces.",
    ],
  },
  "veggie-burger": {
    servings: 4,
    ingredients: [
      { name: "pains burger", quantity: 4, unit: "" },
      { name: "steaks végétaux", quantity: 4, unit: "" },
      { name: "cheddar", quantity: 4, unit: "tranches" },
      { name: "tomate", quantity: 1, unit: "" },
      { name: "salade", quantity: 0.5, unit: "", scalable: false },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "pommes de terre", quantity: 800, unit: "g" },
      { name: "huile", quantity: 2, unit: "c. à soupe" },
      { name: "ketchup", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Cuire les potatoes au four à 220 °C environ 30 minutes.",
      "Cuire les steaks végétaux à la poêle.",
      "Ajouter le cheddar en fin de cuisson.",
      "Toaster les pains et monter les burgers avec légumes et ketchup.",
    ],
  },
  "boulettes-tomate": {
    servings: 4,
    ingredients: [
      { name: "bœuf haché", quantity: 500, unit: "g" },
      { name: "œuf", quantity: 1, unit: "" },
      { name: "chapelure", quantity: 50, unit: "g" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "passata", quantity: 500, unit: "g" },
      { name: "gousse d'ail", quantity: 1, unit: "" },
      { name: "origan", quantity: 1, unit: "c. à café" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "spaghetti", quantity: 300, unit: "g" },
    ],
    steps: [
      "Mélanger bœuf, œuf, chapelure, sel et poivre. Former les boulettes.",
      "Les faire dorer dans l'huile puis les réserver.",
      "Faire revenir ail et oignon, ajouter la passata et l'origan.",
      "Remettre les boulettes et mijoter 15 minutes. Servir avec les spaghetti.",
    ],
  },
  "saucisses-lentilles": {
    servings: 4,
    ingredients: [
      { name: "saucisses", quantity: 8, unit: "" },
      { name: "lentilles vertes", quantity: 300, unit: "g" },
      { name: "carottes", quantity: 2, unit: "" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "feuille de laurier", quantity: 1, unit: "" },
      { name: "bouillon", quantity: 800, unit: "ml" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Rincer les lentilles.",
      "Faire revenir oignon et carottes dans l'huile.",
      "Ajouter lentilles, bouillon et laurier et cuire 25 minutes.",
      "Ajouter les saucisses et poursuivre 15 minutes environ jusqu'à cuisson complète.",
    ],
  },
  "blanquette-veau": {
    servings: 4,
    ingredients: [
      { name: "veau à mijoter", quantity: 700, unit: "g" },
      { name: "carottes", quantity: 3, unit: "" },
      { name: "champignons", quantity: 250, unit: "g" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "bouquet garni", quantity: 1, unit: "" },
      { name: "bouillon", quantity: 700, unit: "ml" },
      { name: "crème", quantity: 20, unit: "cl" },
      { name: "jaune d'œuf", quantity: 1, unit: "" },
      { name: "farine", quantity: 30, unit: "g" },
      { name: "beurre", quantity: 30, unit: "g" },
    ],
    steps: [
      "Faire revenir le veau sans trop colorer, puis couvrir de bouillon. Ajouter oignon et bouquet garni et mijoter 1 heure.",
      "Ajouter carottes puis champignons et cuire encore 25 minutes.",
      "Faire un roux avec beurre et farine, ajouter un peu de bouillon puis remettre dans la cocotte.",
      "Hors du feu, mélanger crème et jaune d'œuf puis incorporer sans faire bouillir.",
    ],
  },
  "aligot-saucisse": {
    servings: 4,
    ingredients: [
      { name: "pommes de terre", quantity: 1.2, unit: "kg" },
      { name: "tome fraîche", quantity: 300, unit: "g" },
      { name: "crème", quantity: 20, unit: "cl" },
      { name: "beurre", quantity: 50, unit: "g" },
      { name: "saucisses", quantity: 8, unit: "" },
      { name: "gousse d'ail", quantity: 1, unit: "" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Cuire les pommes de terre puis les écraser.",
      "Ajouter beurre, crème et ail.",
      "Incorporer la tome en morceaux à feu doux en tirant la purée jusqu'à obtenir une texture filante.",
      "Cuire les saucisses à la poêle et servir avec l'aligot.",
    ],
  },
  "brandade-morue": {
    servings: 4,
    ingredients: [
      { name: "morue dessalée", quantity: 600, unit: "g" },
      { name: "pommes de terre", quantity: 800, unit: "g" },
      { name: "lait", quantity: 20, unit: "cl" },
      { name: "huile d'olive", quantity: 10, unit: "cl" },
      { name: "gousses d'ail", quantity: 2, unit: "" },
      { name: "persil", quantity: 1, unit: "bouquet" },
      { name: "poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Cuire les pommes de terre puis les écraser.",
      "Pocher la morue dans le lait quelques minutes puis l'effeuiller.",
      "Mélanger pommes de terre, morue, ail, persil et huile d'olive progressivement.",
      "Mettre dans un plat et gratiner à 200 °C environ 15 minutes.",
    ],
  },
  "endives-jambon": {
    servings: 4,
    ingredients: [
      { name: "endives", quantity: 8, unit: "" },
      { name: "jambon", quantity: 8, unit: "tranches" },
      { name: "béchamel", quantity: 50, unit: "cl" },
      { name: "fromage râpé", quantity: 100, unit: "g" },
      { name: "beurre", quantity: 20, unit: "g" },
      { name: "sel, poivre et muscade", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Cuire les endives à la vapeur ou à l'eau puis bien les égoutter.",
      "Enrouler chaque endive dans une tranche de jambon et placer dans un plat beurré.",
      "Napper de béchamel et parsemer de fromage.",
      "Gratiner à 200 °C 20 minutes.",
    ],
  },
  "gnocchis-poelee": {
    servings: 4,
    ingredients: [
      { name: "gnocchis", quantity: 800, unit: "g" },
      { name: "tomates cerises", quantity: 300, unit: "g" },
      { name: "boules de mozzarella", quantity: 2, unit: "" },
      { name: "gousses d'ail", quantity: 2, unit: "" },
      { name: "huile d'olive", quantity: 2, unit: "c. à soupe" },
      { name: "origan", quantity: 1, unit: "c. à café" },
      { name: "basilic", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Faire dorer les gnocchis dans l'huile selon le temps indiqué.",
      "Ajouter ail et tomates cerises et cuire jusqu'à ce qu'elles commencent à éclater.",
      "Ajouter mozzarella en morceaux et origan.",
      "Couvrir 2 minutes pour faire fondre le fromage puis ajouter le basilic.",
    ],
  },
  "chakchouka-pois-chiche": {
    servings: 4,
    ingredients: [
      { name: "pois chiches", quantity: 400, unit: "g" },
      { name: "épinards", quantity: 300, unit: "g" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "gousses d'ail", quantity: 2, unit: "" },
      { name: "tomates concassées", quantity: 400, unit: "g" },
      { name: "cumin", quantity: 1, unit: "c. à café" },
      { name: "huile", quantity: 2, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Faire revenir oignon et ail dans l'huile.",
      "Ajouter tomates et cumin et mijoter 10 minutes.",
      "Ajouter les pois chiches puis les épinards et cuire jusqu'à ce qu'ils tombent.",
      "Rectifier l'assaisonnement et servir avec du pain.",
    ],
  },
  "nouilles-sautees-poulet": {
    servings: 4,
    ingredients: [
      { name: "nouilles asiatiques", quantity: 250, unit: "g" },
      { name: "poulet", quantity: 500, unit: "g" },
      { name: "carotte", quantity: 1, unit: "" },
      { name: "poivron", quantity: 1, unit: "" },
      { name: "courgette", quantity: 1, unit: "" },
      { name: "gousses d'ail", quantity: 2, unit: "" },
      { name: "sauce soja", quantity: 3, unit: "c. à soupe" },
      { name: "huile de sésame", quantity: 1, unit: "c. à soupe" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
    ],
    steps: [
      "Cuire les nouilles selon le paquet et les égoutter.",
      "Faire sauter le poulet dans l'huile.",
      "Ajouter les légumes et l'ail et cuire 5 à 6 minutes.",
      "Ajouter les nouilles, sauce soja et huile de sésame. Faire sauter 2 minutes.",
    ],
  },
  "cordon-bleu-airfryer": {
    servings: 4,
    ingredients: [
      { name: "escalopes de poulet fines", quantity: 4, unit: "" },
      { name: "jambon", quantity: 4, unit: "tranches" },
      { name: "fromage", quantity: 120, unit: "g" },
      { name: "chapelure", quantity: 80, unit: "g" },
      { name: "farine", quantity: 40, unit: "g" },
      { name: "œufs", quantity: 2, unit: "" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Aplatir légèrement les escalopes. Déposer jambon et fromage puis refermer.",
      "Passer dans farine, œuf puis chapelure.",
      "Déposer dans l'Airfryer, arroser légèrement d'huile et cuire à 190 °C environ 15 minutes en retournant à mi-cuisson.",
      "Cuire les haricots verts à la vapeur ou à l'eau et servir avec les cordons bleus.",
    ],
  },
  "moussaka": {
    servings: 4,
    ingredients: [
      { name: "bœuf ou d'agneau haché", quantity: 500, unit: "g" },
      { name: "aubergines", quantity: 2, unit: "" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "tomates concassées", quantity: 400, unit: "g" },
      { name: "béchamel", quantity: 40, unit: "cl" },
      { name: "fromage râpé", quantity: 50, unit: "g" },
      { name: "huile", quantity: 2, unit: "c. à soupe" },
      { name: "origan", quantity: 1, unit: "c. à café" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Couper les aubergines en tranches et les faire griller ou rôtir avec un peu d'huile.",
      "Faire revenir oignon et viande puis ajouter tomates et origan. Mijoter 15 minutes.",
      "Alterner aubergines et viande dans un plat.",
      "Couvrir de béchamel et fromage puis cuire à 190 °C environ 35 minutes.",
    ],
  },
  "risotto-butternut": {
    servings: 4,
    ingredients: [
      { name: "riz arborio", quantity: 300, unit: "g" },
      { name: "butternut", quantity: 500, unit: "g" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "bouillon", quantity: 1, unit: "l" },
      { name: "vin blanc", quantity: 10, unit: "cl" },
      { name: "parmesan", quantity: 40, unit: "g" },
      { name: "beurre", quantity: 30, unit: "g" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
    ],
    steps: [
      "Faire revenir oignon et butternut en petits dés dans l'huile.",
      "Ajouter le riz et nacrer 2 minutes.",
      "Ajouter vin puis bouillon progressivement en remuant jusqu'à cuisson du riz.",
      "Hors du feu, ajouter beurre et parmesan.",
    ],
  },
  "pizza-blanche-chevre": {
    servings: 4,
    ingredients: [
      { name: "pâte à pizza", quantity: 1, unit: "", scalable: false },
      { name: "crème fraîche", quantity: 150, unit: "g" },
      { name: "chèvre", quantity: 200, unit: "g" },
      { name: "mozzarella", quantity: 100, unit: "g" },
      { name: "miel", quantity: 2, unit: "c. à soupe" },
      { name: "noix", quantity: 1, unit: "poignée" },
      { name: "poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Préchauffer le four à 240 °C.",
      "Étaler la pâte et tartiner de crème.",
      "Ajouter chèvre et mozzarella puis poivrer.",
      "Cuire 10 à 12 minutes. À la sortie du four, ajouter miel et noix concassées.",
    ],
  },
  "poulet-teriyaki": {
    servings: 4,
    ingredients: [
      { name: "poulet", quantity: 600, unit: "g" },
      { name: "riz", quantity: 250, unit: "g" },
      { name: "brocoli", quantity: 1, unit: "" },
      { name: "sauce soja", quantity: 3, unit: "c. à soupe" },
      { name: "miel", quantity: 2, unit: "c. à soupe" },
      { name: "vinaigre de riz", quantity: 1, unit: "c. à soupe" },
      { name: "gingembre râpé", quantity: 1, unit: "c. à café" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
    ],
    steps: [
      "Cuire le riz et le brocoli.",
      "Couper le poulet et le faire dorer dans l'huile.",
      "Mélanger soja, miel, vinaigre et gingembre puis verser sur le poulet.",
      "Laisser réduire 3 à 5 minutes jusqu'à obtenir une sauce brillante. Servir avec riz et brocoli.",
    ],
  },
  "gratin-brocoli": {
    servings: 4,
    ingredients: [
      { name: "pommes de terre", quantity: 700, unit: "g" },
      { name: "brocoli", quantity: 500, unit: "g" },
      { name: "béchamel", quantity: 40, unit: "cl" },
      { name: "fromage râpé", quantity: 120, unit: "g" },
      { name: "beurre", quantity: 20, unit: "g" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Cuire pommes de terre et brocoli jusqu'à ce qu'ils soient presque tendres.",
      "Mettre dans un plat beurré.",
      "Napper de béchamel et parsemer de fromage.",
      "Gratiner à 200 °C environ 20 minutes.",
    ],
  },
  "tacos-poisson": {
    servings: 4,
    ingredients: [
      { name: "poisson blanc", quantity: 600, unit: "g" },
      { name: "tortillas", quantity: 8, unit: "" },
      { name: "chou rouge", quantity: 0.5, unit: "" },
      { name: "tomates", quantity: 2, unit: "" },
      { name: "avocat", quantity: 1, unit: "" },
      { name: "yaourt grec", quantity: 150, unit: "g" },
      { name: "citron vert", quantity: 1, unit: "" },
      { name: "paprika", quantity: 1, unit: "c. à café" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
    ],
    steps: [
      "Couper le poisson en morceaux et l'assaisonner de paprika, sel et poivre.",
      "Le cuire dans l'huile 6 à 8 minutes.",
      "Mélanger le yaourt avec le jus de citron vert.",
      "Garnir les tortillas de chou, tomate, avocat, poisson et sauce.",
    ],
  },
  "soupe-oignon": {
    servings: 4,
    ingredients: [
      { name: "gros oignons", quantity: 5, unit: "" },
      { name: "bouillon de bœuf ou légumes", quantity: 1, unit: "l" },
      { name: "beurre", quantity: 40, unit: "g" },
      { name: "farine", quantity: 1, unit: "c. à soupe" },
      { name: "pain", quantity: 8, unit: "tranches" },
      { name: "gruyère râpé", quantity: 120, unit: "g" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Émincer les oignons et les faire fondre dans le beurre 20 minutes jusqu'à ce qu'ils soient bien dorés.",
      "Ajouter la farine et mélanger.",
      "Verser le bouillon et mijoter 20 minutes.",
      "Verser dans des bols, poser le pain et le fromage puis gratiner sous le gril.",
    ],
  },
  "chili-sin-carne-airfryer": {
    servings: 4,
    ingredients: [
      { name: "grosses pommes de terre", quantity: 4, unit: "" },
      { name: "avocats", quantity: 2, unit: "" },
      { name: "citron vert", quantity: 1, unit: "" },
      { name: "tomate", quantity: 1, unit: "" },
      { name: "oignon rouge", quantity: 0.5, unit: "" },
      { name: "haricots rouges", quantity: 1, unit: "boîte" },
      { name: "paprika", quantity: 1, unit: "c. à café" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Piquer les pommes de terre et les cuire dans l'Airfryer à 200 °C jusqu'à ce qu'elles soient tendres, environ 35 à 45 minutes.",
      "Écraser les avocats avec le citron vert, sel et poivre.",
      "Réchauffer les haricots avec paprika.",
      "Ouvrir les pommes de terre et garnir de haricots, guacamole, tomate et oignon.",
    ],
  },
  "spaghetti-vongole": {
    servings: 4,
    ingredients: [
      { name: "spaghetti", quantity: 400, unit: "g" },
      { name: "palourdes ou coques", quantity: 1, unit: "kg" },
      { name: "gousses d'ail", quantity: 3, unit: "" },
      { name: "vin blanc", quantity: 15, unit: "cl" },
      { name: "persil", quantity: 1, unit: "bouquet" },
      { name: "huile d'olive", quantity: 4, unit: "c. à soupe" },
      { name: "piment doux ou poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Rincer soigneusement les coquillages.",
      "Cuire les spaghetti très al dente.",
      "Faire revenir ail dans l'huile, ajouter les coquillages et le vin. Couvrir jusqu'à ouverture.",
      "Ajouter les pâtes, un peu d'eau de cuisson et le persil. Mélanger rapidement et servir.",
    ],
  },
  "curry-crevettes": {
    servings: 4,
    ingredients: [
      { name: "crevettes décortiquées", quantity: 500, unit: "g" },
      { name: "lait de coco", quantity: 400, unit: "ml" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "courgette", quantity: 1, unit: "" },
      { name: "poivron", quantity: 1, unit: "" },
      { name: "pâte de curry doux", quantity: 2, unit: "c. à soupe" },
      { name: "riz", quantity: 250, unit: "g" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
    ],
    steps: [
      "Cuire le riz.",
      "Faire revenir oignon, courgette et poivron dans l'huile.",
      "Ajouter la pâte de curry et le lait de coco.",
      "Ajouter les crevettes et mijoter 5 à 6 minutes. Servir avec le riz.",
    ],
  },
  "pommes-terre-raclette-four": {
    servings: 4,
    ingredients: [
      { name: "pommes de terre", quantity: 1, unit: "kg" },
      { name: "fromage à raclette", quantity: 200, unit: "g" },
      { name: "jambon", quantity: 200, unit: "g" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "crème", quantity: 10, unit: "cl" },
      { name: "poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Cuire les pommes de terre puis les couper en rondelles.",
      "Faire revenir l'oignon et ajouter le jambon.",
      "Dans un plat, alterner pommes de terre, jambon et crème.",
      "Couvrir de fromage à raclette et gratiner à 200 °C 15 à 20 minutes.",
    ],
  },
  "salade-poulet-avocat": {
    servings: 4,
    ingredients: [
      { name: "poulet", quantity: 500, unit: "g" },
      { name: "avocats", quantity: 2, unit: "" },
      { name: "salade", quantity: 1, unit: "", scalable: false },
      { name: "tomates cerises", quantity: 250, unit: "g" },
      { name: "concombre", quantity: 1, unit: "" },
      { name: "citron", quantity: 1, unit: "" },
      { name: "huile d'olive", quantity: 2, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Faire dorer le poulet en morceaux dans un peu d'huile.",
      "Couper avocat, concombre et tomates.",
      "Assembler avec la salade.",
      "Assaisonner avec citron, huile, sel et poivre et ajouter le poulet tiède.",
    ],
  },
  "veloute-brocoli": {
    servings: 4,
    ingredients: [
      { name: "brocoli", quantity: 700, unit: "g" },
      { name: "pommes de terre", quantity: 2, unit: "" },
      { name: "oignon", quantity: 1, unit: "" },
      { name: "bouillon", quantity: 800, unit: "ml" },
      { name: "crème", quantity: 10, unit: "cl" },
      { name: "huile", quantity: 1, unit: "c. à soupe" },
      { name: "sel et poivre", quantity: 0, unit: "", scalable: false },
    ],
    steps: [
      "Faire revenir l'oignon dans l'huile.",
      "Ajouter brocoli, pommes de terre et bouillon.",
      "Cuire 20 à 25 minutes.",
      "Mixer finement puis ajouter la crème.",
    ],
  },
  "smoothie-bowl": {
    servings: 4,
    ingredients: [
      { name: "bananes", quantity: 4, unit: "" },
      { name: "fruits rouges surgelés", quantity: 300, unit: "g" },
      { name: "yaourt grec", quantity: 300, unit: "g" },
      { name: "lait", quantity: 100, unit: "ml" },
      { name: "granola", quantity: 120, unit: "g" },
      { name: "kiwis", quantity: 2, unit: "" },
      { name: "graines", quantity: 2, unit: "c. à soupe" },
    ],
    steps: [
      "Mixer bananes, fruits rouges, yaourt et lait jusqu'à obtenir une texture épaisse.",
      "Répartir dans 4 bols.",
      "Ajouter granola, kiwi en morceaux et graines.",
      "Servir immédiatement.",
    ],
  },
};
